### ISSUE TITLE
type incompatible

### ISSUE THREAD

**Issue by qtisan** [swimauger/tensorset#2]
```
classifier.setClassifierDataset(dataset);
```
The code above will cause the type incompatible as follow: (Typescript)
```
const dataset: {
    [label: string]: Tensor2D;
}
Argument of type '{ [label: string]: import("/ml-project/node_modules/tensorset/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor2D; }' is not assignable to parameter of type '{ [label: string]: import("/ml-project/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor2D; }'.
  Index signatures are incompatible.
    Type 'import("/ml-project/node_modules/tensorset/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor2D' is not assignable to type 
'import("/ml-project/node_modules/@tensorflow/tfjs-core/dist/tensor").Tensor2D'.
      Property 'isDisposedInternal' is protected but type 'Tensor<R>' is not a class derived from 'Tensor<R>'.ts(2345)
```
With `as any` can ignore this, but it make uncomfortable.
```
classifier.setClassifierDataset(dataset as any);
```

**Comment by qtisan** [comment]
Maybe it caused by `import Tensorset from 'tensorset/lib/Tensorset';`
Replace the `import` statement with `const Tensorset = require('tensorset');` is ok!

**Comment by swimauger** [comment]
Hi @qtisan, thanks for the first issue!

I believe the most recent update to `1.2.9` should help resolve your issue there, but you may want to delete node_modules before installing 👍 

I am going to close the issue, but if you have any more problems related to this please ask.

Happy Coding! 👨‍💻
